name: Update Profile Activity

"on":
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate contribution card
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          include-title: "false"
          colors: light
          hide-keys: "general, languages, repositories"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
